version: "3.8"
services:
  server0:
    build:
      context: .
    ports:
      - 50001:50001
      - 50002:50002
    environment:
      SERVER_ID: server0
      ADVERTISE_ADDR: server0:50000
      GRPC_ADDR: :50001
      GRPC_GATEWAY_ADDR: :50002
      DATA_DIR: /raftkv/data/server0
    networks:
      - default
  server1:
    build:
      context: .
    ports:
      - 50102:50102
    environment:
      SERVER_ID: server1
      ADVERTISE_ADDR: server1:50100
      JOIN_ADDR: server0:50001
      GRPC_ADDR: :50101
      GRPC_GATEWAY_ADDR: :50102
      DATA_DIR: /raftkv/data/server1
    networks:
      - default
  server2:
    build:
      context: .
    ports:
      - 50202:50202
    environment:
      SERVER_ID: server2
      ADVERTISE_ADDR: server2:50200
      JOIN_ADDR: server0:50001
      GRPC_ADDR: :50201
      GRPC_GATEWAY_ADDR: :50202
      DATA_DIR: /raftkv/data/server2
    networks:
      - default
